name: Main workflow

on:
push:
    branches:
    - raw

jobs:
build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
    uses: feng138168/hexo-blog@master
    with:
        node-version: '10.x'
    - name: prepare build env
    env:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        NEXT_VERSION: v7.3.0
    run: |
        mkdir -p ~/.ssh/
        echo "$ACCESS_TOKEN" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name 'daizhoufeng'
        git config --global user.email '893616132@qq.com
        npm i -g hexo-cli
        npm i
        git clone --branch ${NEXT_VERSION} --depth=10  git@github.com:theme-next/hexo-theme-next.git themes/next
        git checkout -b ${NEXT_VERSION}
        git clone git@github.com:theme-next/theme-next-three --depth=1 themes/next/source/lib/three
        git clone git@github.com:theme-next/theme-next-reading-progress --depth=1 themes/next/source/lib/reading_progress
        git clone git@github.com:theme-next/theme-next-algolia-instant-search --depth=1 themes/next/source/lib/algolia-instant-search
        # git clone git@github.com:theme-next/theme-next-fancybox3  --depth=1 themes/next/source/lib/fancybox
        git clone git@github.com:theme-next/theme-next-pace --depth=1 themes/next/source/lib/pace
    - name: deploy to github
    env:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
    run: |
        hexo generate && hexo algolia && hexo deploy